game/urls.py
from django.urls import path

from . import views


app_name = 'game'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('create_game/', views.createGame, name='create_game'),
    path('join/', views.assignedGames, name='join'),
    path('demand/<int:game_id>', views.createDemand, name='demand'),
    path('role/<int:role_id>', views.enterGame, name='enterGame'),
    path('delete/game/<int:game_id>', views.deleteGame, name='deleteGame'),
    path('monitor/games', views.monitorGames, name='monitorGames'),
    path('admin/plots/<int:game_id>', views.adminPlots, name ='adminPlots'),
    path('start/game/<int:game_id>', views.startGame, name='startGame'),
    path('insights/game/<int:game_id>', views.gameInsights, name='gameInsights'),
    path('update/game/<int:game_id>', views.updateGame, name='updateGame'),
    path('account_settings/', views.accountSettings, name ='accountSettings'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('game.urls')),
    path('admin/', admin.site.urls),
]

game/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Week(models.Model):
    number = models.IntegerField()
    date = models.DateTimeField()
    inventory = models.IntegerField(default= 0)
    backlog = models.IntegerField(default= 0)
    demand = models.IntegerField(default= 0)
    incoming_shipment = models.IntegerField(default= 0)
    outgoing_shipment = models.IntegerField(default= 0)
    order_placed = models.IntegerField(default= -1)
    cost = models.IntegerField(default= 0)
    def __str__(self):
        return str(self.number)


class Role(models.Model):
    role_name = models.CharField(max_length=20)
    downstream_player = models.IntegerField(default=0)
    upstream_player = models.IntegerField(default=0)
    weeks = models.ManyToManyField(
        Week, 
        through='RoleWeek',
        # through_fields=('role_id', 'week_id'),
    )
    def __str__(self):
        return self.role_name


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_instructor = models.BooleanField(default=False)
    roles=models.ManyToManyField(
        Role,
        through='UserRole',
        # through_fields=('user_id', 'role_id'),
    )
    def __str__(self):
        return self.user.username


class Game(models.Model):
    admin = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    nr_rounds = models.IntegerField()
    distributor_present = models.BooleanField(default=True)
    wholesaler_present = models.BooleanField(default=True)
    holding_cost = models.IntegerField()
    backlog_cost = models.IntegerField()
    is_active = models.BooleanField(default=False)
    info_sharing = models.BooleanField(default=True)
    info_delay = models.IntegerField()
    rounds_completed = models.IntegerField(default=0)
    is_completed = models.BooleanField(default=False)
    starting_inventory = models.IntegerField()
    roles=models.ManyToManyField(
        Role,
        through='GameRole',
        # through_fields=('user_id', 'role_id'),
    )
    def __str__(self):
        return str(self.nr_rounds)


class GameRole(models.Model):
    """
    A class that stores user ids and role ids
    """
    game = models.ForeignKey(Game, on_delete=models.CASCADE, db_column='game_id')
    role = models.ForeignKey(Role, on_delete=models.CASCADE, db_column='role_id')


class UserRole(models.Model):
    """
    A class that stores user ids and role ids
    """
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, db_column='user_id')
    role = models.ForeignKey(Role, on_delete=models.CASCADE, db_column='role_id')


class RoleWeek(models.Model):
    role = models.ForeignKey(Role, on_delete=models.CASCADE, db_column='role_id')
    week = models.ForeignKey(Week, on_delete=models.CASCADE, db_column='week_id')   

game/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
import datetime
import matplotlib.pyplot as plt
from io import StringIO
import numpy as np

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import *
from .forms import *


def registerPage(request):
    if request.method == "POST":
        form = ExtendedUserCreationForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
                   
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
          
            return redirect('game:login')
    else:
        form = ExtendedUserCreationForm()
        profile_form = UserProfileForm()	
    
    context = {'form':form, 'profile_form': profile_form}
    return render(request, 'game/register.html', context)



def loginPage(request):
    if request.user.is_authenticated:
	    return redirect('game:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password =request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('game:home')
            else:
                messages.info(request, 'Username OR password is incorrect')
        
        context = {}
        return render(request, 'game/login.html', context)



def logoutUser(request):
	logout(request)
	return redirect('game:login')



@login_required(login_url='game:login')
def home(request):

    list_roles = Role.objects.filter(userprofile=request.user.userprofile)
    for role in list_roles:
        print(role.role_name)
    game_created = Game.objects.filter(admin=request.user.userprofile)
    context={'message': 'Welcome to the main Page', 'list_roles': list_roles, 'game_created': game_created, 'user': request.user.userprofile}
    return render(request, 'game/main.html', context)

@login_required(login_url='game:login')
def home(request):
    game_created = Game.objects.filter(admin=request.user.userprofile)
    context={'game_created': game_created, 'user': request.user.userprofile}
    return render(request, 'game/main.html', context)

def assignedGames(request):
    list_roles = Role.objects.filter(userprofile=request.user.userprofile)
    for role in list_roles:
        print(role.role_name)

    context={'list_roles': list_roles, 'user': request.user.userprofile}
    return render(request, 'game/assignedGames.html', context)


@login_required(login_url='game:login')
def createGame(request):
    if request.method == "POST":
        form1 = GameCreationForm(request.POST)
        form2 = ExtendedGameCreationForm(request.POST)
        if form1.is_valid() and form2.is_valid():
            # get the data from the forms
            retailer = form2.cleaned_data.get("retailer")
            wholesaler = form2.cleaned_data.get("wholesaler")
            distributor = form2.cleaned_data.get("distributor")
            factory = form2.cleaned_data.get("factory")

            isDistributor = form1.cleaned_data['distributor_present']
            isWholesaler = form1.cleaned_data['wholesaler_present']
            startingInventory = form1.cleaned_data['starting_inventory']
            nrRounds = form1.cleaned_data['nr_rounds']


            # ## check for the errors
            # # check if we have selected more than specified
            if(isDistributor==False and distributor):
                messages.info(request, 'Distributor is not selected')
                return render(request, 'game/createGame.html', {})
            if(isWholesaler==False and wholesaler):
                messages.info(request, 'Wholesaler is not selected')
                return render(request, 'game/createGame.html', {})
            #check if the user has selected the same student for more than 1 role
            if(retailer == wholesaler or retailer == distributor or 
            retailer == factory or wholesaler==distributor or wholesaler == factory
            or distributor == factory):
                messages.info(request, 'A student can not have more than 1 role.')
                return render(request, 'game/createGame.html', {})
            


            # #if no errors than save the game, set the admin
            game = form1.save(commit = False)
            user31 = UserProfile.objects.get(user_id=request.user.id)
            game.admin = user31
            game.save()


            #create the respective roles
            r1 = r2 = r3 = r4 = None
            r1 = Role(role_name="retailer")
            r1.save()
            print(r1.id)
            if isDistributor:
                r2 = Role(role_name="wholesaler")
                r2.save()
                r1.upstream_player = r2.id
                r2.downstream_player = r1.id
            if isWholesaler:
                r3 = Role(role_name="distributor")
                r3.save()
                if isDistributor:
                    r2.upstream_player = r3.id
                    r3.downstream_player = r2.id
            r4 = Role(role_name="factory")
            r4.save()
            if isWholesaler:
                r4.downstream_player = r3.id
                r3.upstream_player = r4.id

            r1.save()
            if(r2): r2.save()
            if(r3): r3.save()
            r4.save()

            #add the roles to the userProfile and the game
            user1 = UserProfile.objects.get(user__pk=retailer.id)
            user1.roles.add(r1)
            user4 = UserProfile.objects.get(user__pk=factory.id)
            user4.roles.add(r4)
            game.roles.add(r1, r4)

            if r2 != None:
                user2 = UserProfile.objects.get(user__pk=distributor.id)
                user2.roles.add(r2)
                game.roles.add(r2)
            if r3 != None:
                user3 = UserProfile.objects.get(user__pk=wholesaler.id)
                user3.roles.add(r3)
                game.roles.add(r3)


            #create the weeks, with the respective times, number and starting inventory
            # and add them to the role
            for i in range(nrRounds):
                week1 = Week(date=timezone.now()+datetime.timedelta(minutes=i*3), number= i+1, inventory=startingInventory)
                week1.save()
                r1.weeks.add(week1)
                if(r2): 
                    week2 = Week(date=timezone.now()+datetime.timedelta(minutes=i*3), number= i+1, inventory=startingInventory)
                    week2.save()
                    r2.weeks.add(week2)
                if(r3): 
                    week3 = Week(date=timezone.now()+datetime.timedelta(minutes=i*3), number= i+1, inventory=startingInventory)
                    week3.save()
                    r3.weeks.add(week3)
                week4 = Week(date=timezone.now()+datetime.timedelta(minutes=i*3), number= i+1, inventory=startingInventory)
                week4.save()
                r4.weeks.add(week4)
    
            return HttpResponseRedirect(reverse('game:demand', args=(game.id,)))
    else:
        form2 = ExtendedGameCreationForm()
        form1 = GameCreationForm()	
    
    context = {'form1':form1, 'form2':form2, 'user': request.user.userprofile}
    return render(request, 'game/createGame.html', context)


@login_required(login_url='game:login')
def createDemand(request, game_id):
    game = Game.objects.get(pk=game_id)
    if request.method == "POST":
        text = request.POST['demand']
        demands = text.split(", ")
        if len(demands) != game.nr_rounds:
            messages.info(request, 'You have not specified all rounds')
            return HttpResponseRedirect(reverse('game:demand', args=(game_id,)))
        
        k=1
        for customer_demand in demands:
            week1 = Week.objects.get(role__game=game, number=k, role__role_name="retailer")
            week1.demand = customer_demand
            week1.save()
            k+=1
        return redirect('game:home')

    context = {'game': game, 'user': request.user.userprofile}
    return render(request, 'game/demandPattern.html', context)


# helper function for constructing the graph
def return_graph(last_weeks, dataType):
    if(last_weeks):
        inventories = []
        demands = []
        incoming_shipments = []
        outgoing_shipments = []
        orders = []
        weeknr = []
        if(dataType == 'inventory'):
            i = 0
            for week in last_weeks:
                inventories.append(week.inventory-week.backlog)
                i+=1
                weeknr.append(i)
            fig = plt.figure()
            plt.ylabel('Inventory')
            # plt.xlabel('Week Nr')
            plt.title('Inventory')
            plt.plot(weeknr,inventories)
        elif dataType == 'demand':
            i = 0
            for week in last_weeks:
                demands.append(week.demand)
                i+=1
                weeknr.append(i)
            fig = plt.figure()
            plt.ylabel('Demand')
            # plt.xlabel('Week Nr')
            plt.title('Demand')
            plt.plot(weeknr,demands)
        elif dataType == 'incoming_shipment':
            i = 0
            for week in last_weeks:
                incoming_shipments.append(week.incoming_shipment)
                i+=1
                weeknr.append(i)
            fig = plt.figure()
            plt.ylabel('Incoming Shipment')
            # plt.xlabel('Week Nr')
            plt.title('Incoming Shipment')

game/views/userview.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
import datetime
import matplotlib.pyplot as plt
from io import StringIO

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from game.models import *
from game.forms import *


def registerPage(request):
    if request.method == "POST":
        form = ExtendedUserCreationForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
                   
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
          
            return redirect('game:login')
    else:
        form = ExtendedUserCreationForm()
        profile_form = UserProfileForm()	
    
    context = {'form':form, 'profile_form': profile_form}
    return render(request, 'game/register.html', context)



def loginPage(request):
    if request.user.is_authenticated:
	    return redirect('game:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password =request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('game:home')
            else:
                messages.info(request, 'Username OR password is incorrect')
        
        context = {}
        return render(request, 'game/login.html', context)



def logoutUser(request):
	logout(request)
	return redirect('game:login')


@login_required(login_url='game:login')
def home(request):
    game_created = Game.objects.filter(admin=request.user.userprofile)
    context={'game_created': game_created, 'user': request.user.userprofile}
    return render(request, 'game/main.html', context)

@login_required(login_url='game:login')
def assignedGames(request):
    list_roles = Role.objects.filter(userprofile=request.user.userprofile)
    context={'list_roles': list_roles, 'user': request.user.userprofile}
    return render(request, 'game/assignedGames.html', context)

@login_required(login_url='game:login')
def accountSettings(request):
    context={'user': request.user.userprofile}
    return render(request, 'game/accountSettings.html', context)

game/templates/game/assignedGames.html
{% extends 'game/navbar.html' %}

{% block content %}

<!-- Main content -->
<div class="main-container">
    <h2>Assigned Games</h2>
    <p>Here you can view and join all assigned games to you.</p>

    <hr>

    <div class="form-container py-2">
        <div class="card rounded-5 border-0 shadow">
            <div class="card-body p-5">
                <!-- ASSIGNED GAMES -->
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Game ID</th>
                                    <th>Current Week</th>
                                    <th>Role Name</th>
                                    <th>Active</th>
                                    <th>Completed</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                {% if list_roles %}
                                    {% for role in list_roles %}
                                        {% for game in role.game_set.all%}
                                            <tr>
                                                <th scope="row">{{game.id}}</td>
                                                <td >{{game.rounds_completed}}</td>
                                                <td style="text-transform: uppercase;">{{role.role_name}}</td>
                                                <td>{{ game.is_active }}</td>
                                                <td>{{game.is_completed}}</td>
                                                <td>
                                                    <a href="{% url 'game:enterGame' role.id %}">{%if game.is_completed == False %}<i class="nav-icons fas fa-sign-in-alt"></i>Enter Game{%else%}<i class="nav-icons far fa-eye"></i>View Game{%endif%}</a></td>
                                                </td>
                                                <td>
                                                {%if game.is_completed == True %}
                                                    <a href="{% url 'game:gameInsights' game.id %}"><i class="nav-icons fas fa-chart-line"></i>View Insights</a></td>
                                                {%endif%}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    {% endfor %}
                                {% else %}
                                    <p>There are no games to display</p>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
// Sets current link as active
$('#join-link').addClass('active');
</script>

{% endblock %}

game/templates/game/main.html
{% extends 'game/navbar.html' %}

{% block content %}
<div class="header-image">
    <p class="welcome-text">Welcome {{user.user.username}}</p>
</div>

<!-- Main content -->
<div class="main-container">
    <h2>Created Games</h2>
    <p>Here you can view, edit and delete all the games you have created. To join games, go to the "Join" tab.</p>
    <hr>

    <div class="form-container py-2">
        <div class="card rounded-5 border-0 shadow">
            <div class="card-body p-5">
                <!-- CREATED GAMES -->                

                <div class="cu-btns">
                    <a href="{% url 'game:create_game'%}" style="background-color: #59bd60; transition: 0.2s;"><i class="nav-icons fas fa-plus-circle"></i>Create Game</a>
                </div>

                <!--  Bootstrap table-->
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                            <!-- Columns based on the screenshot prof. Chankov shows
                                but could be customized according to the game model -->
                                <th scope="col">ID</th>
                                <th scope="col">Delay</th>
                                <th scope="col">Has Wholesaler</th>
                                <th scope="col">Has Distributor</th>
                                <th scope="col">Holding Cost</th>
                                <th scope="col">Backlog Cost</th>
                                <th scope="col">Current Week</th>
                                <th scope="col">Week to Stop</th>
                                <th scope="col">Active</th>
                                <!-- These buttons are not implemented -->
                                <!-- <th scope="col">Reset</th>
                                <th scope="col">Freeze</th> -->
                                <!-- Players should show a pop-up modal with the player names, roles and passwords -->
                                <th scope="col">Players</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% if game_created %}
                                {% for game in game_created %}
                                <tr>
                                    <th scope="row">{{game.id}}</td>
                                    <td>{{game.info_delay}} weeks</td>
                                    <td>{% if game.wholesaler_present == True %} Yes {% else %} No {% endif %}</td>
                                    <td>{% if game.distributor_present == True %} Yes {% else %} No {% endif %}</td> 
                                    <td>{{game.holding_cost}}</td> 
                                    <td>{{game.backlog_cost}}</td>
                                    <td>{{game.rounds_completed}}</td> 
                                    <td>{{game.nr_rounds}}</td>
                                    {%if game.is_active == True%}
                                    <td style="color: green;">Yes</td>
                                    {%else%}
                                    <td><a href ="{% url 'game:startGame' game.id %}">Activate</a></td>
                                    {%endif%}
                                    <!-- <td>
                                        <button class="game-btn">Reset</button>
                                    </td>
                                    <td>
                                        <button class="game-btn">Freeze</button> 
                                    </td> -->
                                    <td>
                                        <button type="button" id="modal-btn" class="game-btn" data-toggle="modal" data-target="#Players" 
                                        data-game="{{game.id}}"
                                        data-players="
                                        {%for role in game.roles.all%}
                                            {%for userprof in role.userprofile_set.all%}
                                                <tr>
                                                    <th>{{role.role_name}}</th>
                                                    <td>{{userprof.user}}</td>
                                                </tr>
                                            {%endfor%} 
                                        {%endfor%}
                                        ">Players</button>
                                        <!-- Parsed data to display table inside modal -->
                                        <!-- Modal -->
                                        <div id="Players" class="modal hide" data-backdrop="false">
                                            <div class="modal-dialog modal-dialog-centered">
                                                <div class="modal-content">
                                                    <div class="modal-header d-block" style="cursor: move;">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                        <h5 class="modal-title" id="exampleModalLabel" style="text-align: left;">Players for Game <span id="game-id"></span></h5>
                                                        <!-- <h5 class="modal-title text-center">Game id Players</h5> -->
                                                    </div>
                                                    <div class="modal-body">
                                                        <div id="players-list">
                                                            <table id="players-roles">
                                                                <!-- Players go here -->
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    
                                    <td>
                                        <a href="{% url 'game:deleteGame' game.id %}" class="game-icon" data-toggle="tooltip" data-placement="bottom" title="Delete"><i class="fas fa-trash"></i></a>
                                    </td>
                                    <td>
                                        <a href="{% url 'game:updateGame' game.id %}" class="game-icon" id="edit" data-toggle="tooltip" data-placement="bottom" title="Update"><i class="fas fa-edit"></i></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% else %}
                                <p>There are no games to display</p>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
// Changes modal content depending on game
+$('#Players').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var players = button.data('players')
    var game = button.data('game')
    var modal = $(this)

    modal.find('#game-id').text(game);
    modal.find('#players-roles').html(players);
})

// Makes modal draggable
$("#Players").draggable({
    handle: ".modal-header"
});

// Sets current link as active
$('#create-link').addClass('active');
</script>

{% endblock %}

game/templates/game/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Beer Distribution Game</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="{% static 'game/style.css' %}" />
</head>

<body class="body-dash">

	<!-- Navigation Bar -->
	<nav class="navbar navbar-expand-md navbar-dark sticky-top">
		<div class="d-flex w-50">
			<a class="navbar-brand mr-0" href="/"><i class="nav-icons fas fa-beer"></i></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
				<span class="navbar-toggler-icon"></span>
			</button>
		</div>
		<div class="navbar-collapse collapse justify-content-center" id="collapsingNavbar">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'game:home' %}" id="create-link"><i class="nav-icons fas fa-gamepad"></i>Create</a>
				</li>

				{% if user.is_instructor == False %} 
					<li class="nav-item">
						<a class="nav-link" href="{% url 'game:join' %}" id="join-link"><i class="nav-icons fas fa-sign-in-alt"></i>Join</a>
					</li>
				{% endif %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'game:monitorGames' %}" id="monitor-link"><i class="nav-icons fas fa-eye"></i>Monitor</a>
				</li>
			</ul>
		</div>
		<span class="navbar-text small text-truncate mt-1 w-50 text-right" >
			<a style="color: white; text-decoration: none;" href="{% url 'game:logout'%}">Logout</a>
		</span>
		<span class="mt-1 text-right">
			<a href="{% url 'game:accountSettings'%}" class="settings"><i class="fas fa-cog" style="padding-left: 15px; transform: scale(1.2);" data-toggle="tooltip" data-placement="bottom" title="Account Settings"></i></a>
		</span>
	</nav>

	{% block content %}

  	{% endblock %}

</body>
</html>